[package]
name = "rust-wasm-rand"
version = "0.1.0"
edition = "2021"
keywords = ["rust", "wasm", "pseudo-random", "random"]
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.84"
